# Generated by Django 4.2 on 2023-05-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_agencyphotos_agencyprofile_comment_commentreaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['-date_created'], 'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
    ]
