# Generated by Django 4.2 on 2023-05-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_agency_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
