# Generated by Django 4.2 on 2023-05-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_postreaction_delete_commentreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=9)),
                ('comment_id', models.CharField(max_length=19)),
                ('post_id', models.CharField(max_length=9)),
            ],
        ),
    ]
