# Generated by Django 4.2 on 2023-05-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_commentreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='post_id',
            field=models.CharField(max_length=14),
        ),
    ]
