# Generated by Django 4.2 on 2023-05-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_commentreaction_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyReact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=19)),
                ('user_id', models.CharField(max_length=9)),
                ('reply_id', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_id',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
    ]
