# Generated by Django 4.2 on 2023-05-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_replyreact_reply_reply_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=14)),
                ('read_status', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=9)),
                ('post_notification_id', models.CharField(max_length=20)),
                ('notif_type', models.IntegerField()),
                ('trigger_id', models.CharField(max_length=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
