# Generated by Django 4.2.1 on 2023-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_postnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='administrator',
            field=models.CharField(default='NONE', max_length=50),
        ),
    ]
