# Generated by Django 4.2.1 on 2023-06-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_agency_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
